apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-canary
spec:
  ingressClassName: nginx
  rules:
  - host: canary.wuvikr.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-nginx
            port:
              number: 80
