apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-new
spec:
  selector:
    matchLabels:
      app: my-nginx-new
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx-new
    spec:
      containers:
      - name: my-nginx-new
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: creat-index-html-file
        image: busybox
        command:
        - sh
        - -c
        - echo "this is new version." > /usr/share/nginx/html/index.html
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-new
  labels:
    app: my-nginx-new
spec:
  type: ClusterIP 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx-new
