apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-rewrite
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: rewrite.wuvikr.top
    http:
      paths:
      - backend:
          service:
            name: my-nginx
            port:
              number: 80
        path: /api(/|$)(.*)
        pathType: ImplementationSpecific
