apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-snippet
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      set $agentflag 0;
      if ($http_user_agent ~* "(Android|iPhone|Windows Phone|UC|Kindle)" ){
        set $agentflag 1;
      }
      if ( $agentflag = 1 ) {
        return 301 http://m-snippet.wuvikr.top;
      }
spec:
  ingressClassName: nginx
  rules:
  - host: snippet.wuvikr.top
    http:
      paths:
      - backend:
          service:
            name: laptop
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
